DATABASE_USER: db_user
DATABASE_PWD: db_pwd
DATABASE_SCHEMA: db_schema
BOT_TOKEN: bot_token
BOT_CHATID: bot_chat_id
AUS1: "\U0001F1E6\U0001F1F9 Austria Tipico Bundesliga"
AUS2: "\U0001F1E6\U0001F1F9 Austria Eerste Liga"
BEL1: "\U0001F1E7\U0001F1EA Belgium First Division"
BRA1: "\U0001F1E7\U0001F1F7 Brazil Serie A"
SWI1: "\U0001F1E8\U0001F1ED Switizerland Super League"
CZE1: "\U0001F1E8\U0001F1FF Czech-Republic 1-Liga"
CYP1: "\U0001F1E8\U0001F1FE Cyprus First Division"
DAN1: "\U0001F1E9\U0001F1F0 Denmark Superliga"
GRE1: "\U0001F1EC\U0001F1F7 Greece Super League"
HUN1: "\U0001F1ED\U0001F1FA Hungary Otp-Bank-Liga"
IRE1: "\U0001F1EE\U0001F1EA Ireland Premier Division" 
ISR1: "\U0001F1EE\U0001F1F1 Israel Ligat-Ha-Al"
JAP1: "\U0001F1EF\U0001F1F5 Japan"
MAL1: "\U0001F1F2\U0001F1F9 Malta Premier-League"
OLA1: "\U0001F1F3\U0001F1F1 Holland Eredivisie"
OLA2: "\U0001F1F3\U0001F1F1 Holland Eerste Divisie"
POL1: "\U0001F1F5\U0001F1F1 Poland Ekstraklasa"
POL2: "\U0001F1F5\U0001F1F1 Poland Division-1"
POR1: "\U0001F1F5\U0001F1F9 Portugal Primeira-Liga"
ROM1: "\U0001F1F7\U0001F1F4 Romania Liga-1"
SER1: "\U0001F1F7\U0001F1F8 Serbia Super Liga"
QAT1: "\U0001F1F6\U0001F1E6 Qatar QSL"
RUS1: "\U0001F1F7\U0001F1FA Russia Premier League"
SWE1: "\U0001F1F8\U0001F1EA Sweden Allsvenskan"
SLO1: "\U0001F1F8\U0001F1EE Slovenia Prva-Liga"
SLK1: "\U0001F1F8\U0001F1F0 Slovakia Fortuna Liga"
NOR1: "\U0001F1F3\U0001F1F4 Norway Eliteserien"
SCO1: "\U0001F1EC\U0001F1E7 Scotland Premiership"
TUR2: "\U0001F1F9\U0001F1F7 Turkey Lig2"
TUR1: "\U0001F1F9\U0001F1F7 Turkey Super Lig"
UKR1: "\U0001F1FA\U0001F1E6 Ukraine Premier League"
ITA1: "\U0001F1EE\U0001F1F9 Italy Serie A"
ITA2: "\U0001F1EE\U0001F1F9 Italy Serie B"
ITAC: "\U0001F1EE\U0001F1F9 Italy Cup"
FRA1: "\U0001F1EB\U0001F1F7 France Ligue 1"
FRA2: "\U0001F1EB\U0001F1F7 France Ligue 2"
FRA3: "\U0001F1EB\U0001F1F7 France National"
FRAC: "\U0001F1EB\U0001F1F7 Coupe de France"
ENG1: "\U0001F1EC\U0001F1E7 England Premier League"
ENG3: "\U0001F1EC\U0001F1E7 England League One"
ENG4: "\U0001F1EC\U0001F1E7 England League Two"
SPA1: "\U0001F1EA\U0001F1F8 Spain LaLiga"
SPA2: "\U0001F1EA\U0001F1F8 Spain LaLiga2"
SPAC: "\U0001F1EA\U0001F1F8 Spain Copa del Rey"
ENG2: "\U0001F1EC\U0001F1E7 England Championship"
EUR1: "\U0001F1EA\U0001F1FA Champions League"
EUR2: "\U0001F1EA\U0001F1FA Europa League"
GER1: "\U0001F1E9\U0001F1EA Germany Bundesliga"
GER2: "\U0001F1E9\U0001F1EA Germany Bundesliga 2"
GER3: "\U0001F1E9\U0001F1EA Germany Bundesliga 3"
GERC: "\U0001F1E9\U0001F1EA Germany Cup"
BUL1: "\U0001F1E7\U0001F1EC Bulgaria Parva-Liga"
CRO1: "\U0001F1ED\U0001F1F7 Croatia 1-HNL"
AZE1: "\U0001F1E6\U0001F1FF Azerbaijan Premier League"
USA1: "\U0001F1FA\U0001F1F8 United States MLS"
SPA3A: "\U0001F1EA\U0001F1F8 Spain Segunda-Division B1"
SPA3B: "\U0001F1EA\U0001F1F8 Spain Segunda-Division B2"
SPA3C: "\U0001F1EA\U0001F1F8 Spain Segunda-Division B3"
SPA3D: "\U0001F1EA\U0001F1F8 Spain Segunda-Division B4"
ENGC1: "\U0001F1EC\U0001F1E7 England EFL-Cup"
ENGC1: "\U0001F1EC\U0001F1E7 England FA-Cup"
ITA3A: "\U0001F1EE\U0001F1F9 Italy Serie C Group A"
ITA3B: "\U0001F1EE\U0001F1F9 Italy Serie C Group B"
ITA3C: "\U0001F1EE\U0001F1F9 Italy Serie C Group C"
